services:

  lim:
    image: "fortifydocker/lim:${FORTIFY_DOCKER__LIM:-26.2.ubi.9}"
    profiles:
      - default
      - lim
    labels:
      - traefik.enable=true
      - traefik.http.routers.lim-ftfydemo.rule=Host(`lim.onfortify.com`)
      - traefik.http.routers.lim-ftfydemo.entrypoints=websecure
      - traefik.http.routers.lim-ftfydemo.tls=true
      - traefik.http.routers.lim-ftfydemo.tls.certresolver=le
      - traefik.http.services.lim-ftfydemo.loadbalancer.server.port=80
    # Not exposing ports here - using Traefik to route instead
    #ports:
    #  - "90:80"
    volumes:
      - ftfydata_lim:/app
    restart: always
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "JWT__ValidAudience=FortifyLimAuthAudience"
      - "JWT__ValidIssuer=FortifyLimAuthIssuer"
      - "JWT__SecurityKey=aS1l6IUxmbf9X6PCVpmkG8vraqlpPFU9"
      - "DefaultAdministrator__Login=${LIM_USERNAME:-limadm}"
      - "DefaultAdministrator__FullName=LIM Administrator"
      - "DefaultAdministrator__Password=${LIM_PASSWORD:-F0rtifyPassword!}"
      - "DefaultAdministrator__Email=limadm@scancentral.onfortify.com"
      - "Proxy__Mode=0"
    networks:
      - ftfydemo_net

networks:
  ftfydemo_net:
    external: true
volumes:
  ftfydata_lim: null
