
include:
  - lim/docker-compose.yml
  - ssc/docker-compose.yaml
  - postgres/docker-compose.yml
  - scdast/docker-compose.yml
  #- nexus/docker-compose.yaml
  - scsast/docker-compose.yml
  #- jenkins/docker-compose.yaml
  #- jira/docker-compose.yaml

services:
  traefik:
    image: traefik:${TRAEFIK:-latest}
    profiles:
    - default
    - traefik
    - scdast
    command:
    - --api.dashboard=true
    - --api.insecure=true
    - --entrypoints.web.address=:88
    - --entrypoints.websecure.address=:443
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --certificatesresolvers.le.acme.tlschallenge=true
    - --certificatesresolvers.le.acme.email=${ACME_EMAIL:-admin@onfortify.com}
    - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    - --providers.file.filename=/etc/traefik/dynamic/dynamic_tls.yml
    ports:
    - 88:88
    - 443:443
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - traefik-letsencrypt:/letsencrypt
    - ./certs:/certs:ro
    - ./traefik/dynamic_tls.yml:/etc/traefik/dynamic/dynamic_tls.yml:ro
    networks:
    - ftfydemo_net

networks:
  ftfydemo_net:
    external: true
volumes:
  traefik-letsencrypt: null