services:

  scancentral-sast-controller:
    image: "fortifydocker/scancentral-sast-controller:${SCANCENTRAL_SAST_CONTROLLER_VERSION:-26.2.1}"
    profiles:
      - scsast
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.scancentral-sast-controller.rule=Host(`${SCANCENTRAL_SAST_CONTROLLER_HOSTNAME:-scancentral-sast-controller.onfortify.com}`)
      - traefik.http.routers.scancentral-sast-controller.entrypoints=websecure
      - traefik.http.routers.scancentral-sast-controller.tls=true
      - traefik.http.routers.scancentral-sast-controller.tls.certresolver=le
      - traefik.http.services.scancentral-sast-controller.loadbalancer.server.port=8080
    volumes:
      - ftfydata_scsast_ctrl:/fortify
      - ./secrets:/fortify/secrets:ro
    environment:
      - SCANCENTRAL_WORKER_AUTH_TOKEN_FILE=/fortify/secrets/worker-auth-token
      - SCANCENTRAL_CLIENT_AUTH_TOKEN_FILE=/fortify/secrets/client-auth-token
      - SCANCENTRAL_SSC_SECRET_FILE=/fortify/secrets/ssc-secret
      - SCANCENTRAL_CONFIG_SSC_URL=https://${SSC_HOSTNAME:-ssc.onfortify.com}
      - SCANCENTRAL_CONFIG_THIS_URL=https://${SCANCENTRAL_SAST_CONTROLLER_HOSTNAME:-scancentral-sast-controller.onfortify.com}/scancentral-ctrl
      - SCANCENTRAL_CONFIG_SSC_REMOTE_IP=172.0.0.0/8,10.0.0.0/8
      - SCANCENTRAL_CONFIG_ROUTE_REMOTE_TRANSLATION_TO_NEXT_ODD_SAST_VERSION=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/scancentral-ctrl"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      ssc:
        condition: service_healthy
    networks:
      - ftfydemo_net
  
  scancentral-sast-sensor:
    image: "fortifydocker/scancentral-sast-sensor:${SCANCENTRAL_SAST_SENSOR_VERSION:-26.3.0}"
    profiles:
      - scsast
    restart: always
    depends_on:
      scancentral-sast-controller:
        condition: service_healthy
    volumes:
      - ftfydata_scsast_sensor:/fortify
      - type: bind
        source: ../fortify.license
        target: /app/sca/fortify.license
        read_only: true
      - ./secrets:/run/secrets:ro
    environment:
      - SCANCENTRAL_ENABLE=1
      - SCANCENTRAL_URL=https://scancentral-sast-controller:8443/scancentral-ctrl/
      - SCANCENTRAL_WORKER_AUTH_TOKEN_FILE=/run/secrets/worker-auth-token
      - SCANCENTRAL_TRUSTSTORE_PATH=/run/secrets/sensor-truststore.jks
      - SCANCENTRAL_TRUSTSTORE_PASSWORD_FILE=/run/secrets/sensor-truststore-password
      - FORTIFY_UPDATE_SERVER=https://update.fortify.com
      - FORTIFY_UPDATE_AUTO=1
      - FORTIFY_UPDATE_ACCEPT_KEY=1
    networks:
      - ftfydemo_net

networks:
  ftfydemo_net:
    external: true
volumes:
  ftfydata_scsast_ctrl:
  ftfydata_scsast_sensor:
