services:

  ssc:
    image: "fortifydocker/ssc-webapp:${SSC_VERSION}"
    container_name: ssc
    ports:
      - "${SSC_PORT_EXTERNAL}:${SSC_PORT_INTERNAL}"
    environment:
      JAVA_OPTS: -Xms2g -Xmx4g
      HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD: "${HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD}"
      HTTP_SERVER_CERTIFICATE_KEYSTORE_FILE: "${HTTP_SERVER_CERTIFICATE_KEYSTORE_FILE}"
      HTTP_SERVER_CERTIFICATE_KEY_PASSWORD_FILE: "${HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD_FILE}"
      HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD_FILE: "${HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD_FILE}"
    volumes:
      - ./ssc.autoconfig:/opt/fortify/ssc/ssc.autoconfig:ro
      - ./license:/opt/fortify/ssc/license:ro
      - ./bundles:/opt/fortify/ssc/bundles:ro
      - ./certs:/opt/fortify/ssc/certs:ro
      - ftfydata_ssc_index:/opt/fortify/ssc/index
      - ftfydata_ssc_conf:/opt/fortify/ssc/conf
      - ftfydata_ssc_logs:/usr/local/tomcat/fortify/ssc/logs
    depends_on:
      - mysql-db
    networks:
      - ftfydemo_net

networks:
  ftfydemo_net:
    external: true
volumes:
  mysql_data:
  ftfydata_ssc_index:
  ftfydata_ssc_conf:
  ftfydata_ssc_logs:

